version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: pexcn/docker-images:stretch-linux-kernel
    steps:
      - checkout
      - run:
          name: Run build
          command: sudo bash build.sh
      - store_artifacts:
          path: dist
          destination: packages
