version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: pexcn/docker-images:stretch-linux-kernel
    environment:
      USE_CCACHE: 1
    steps:
      - checkout
      - restore_cache:
          key: cache-v1-{{ checksum "build.sh" }}
      - run:
          name: Run build
          command: bash build.sh
      - save_cache:
          key: cache-v1-{{ checksum "build.sh" }}
          paths:
            - ~/.ccache
      - store_artifacts:
          path: dist
          destination: packages
