version: 2

jobs:
  "4.14.x":
    working_directory: ~/linux-kernel-ci
    docker:
      - image: pexcn/docker-images:stretch-linux-kernel
    environment:
      KERNEL_VERSION: 4.14.151
    steps:
      - checkout
      - run:
          name: Run build
          command: ./build.sh
      - run:
          name: Deploy
          command: ./deploy.sh
      - store_artifacts:
          path: release
          destination: packages
  "5.x":
    working_directory: ~/linux-kernel-ci
    docker:
      - image: pexcn/docker-images:stretch-linux-kernel
    environment:
      KERNEL_VERSION: 5.2.9
    steps:
      - checkout
      - run:
          name: Run build
          command: ./build.sh
      - run:
          name: Deploy
          command: ./deploy.sh
      - store_artifacts:
          path: release
          destination: packages

workflows:
  version: 2
  build:
    jobs:
      - "4.14.x"
      - "5.x"
