version: 2

jobs:
  "4.14.139":
    working_directory: ~/linux-kernel-ci
    docker:
      - image: pexcn/docker-images:stretch-linux-kernel
    environment:
      KERNEL_VERSION: 4.14.139
    steps:
      - checkout
      - run:
          name: Run build
          command: ./build.sh
      - run:
          name: Deploy
          command: ./deploy.sh
      - store_artifacts:
          path: release
          destination: packages
  "4.19.67":
    working_directory: ~/linux-kernel-ci
    docker:
      - image: pexcn/docker-images:stretch-linux-kernel
    environment:
      KERNEL_VERSION: 4.19.67
    steps:
      - checkout
      - run:
          name: Run build
          command: ./build.sh
      - run:
          name: Deploy
          command: ./deploy.sh
      - store_artifacts:
          path: release
          destination: packages
  "5.2.9":
    working_directory: ~/linux-kernel-ci
    docker:
      - image: pexcn/docker-images:stretch-linux-kernel
    environment:
      KERNEL_VERSION: 5.2.9
    steps:
      - checkout
      - run:
          name: Run build
          command: ./build.sh
      - run:
          name: Deploy
          command: ./deploy.sh
      - store_artifacts:
          path: release
          destination: packages

workflows:
  version: 2
  build:
    jobs:
      - "4.14.139"
      - "4.19.67"
      - "5.2.9"
