version: 2

jobs:
  "4.9.162":
    working_directory: ~/code
    docker:
      - image: pexcn/docker-images:stretch-linux-kernel
    environment:
      KERNEL_VERSION: 4.9.162
    steps:
      - checkout
      - run:
          name: Run build
          command: bash build.sh
      - run:
          name: Deploy to GitHub releases
          command: bash release.sh
      - store_artifacts:
          path: release
          destination: packages
  "4.14.105":
    working_directory: ~/code
    docker:
      - image: pexcn/docker-images:stretch-linux-kernel
    environment:
      KERNEL_VERSION: 4.14.105
    steps:
      - checkout
      - run:
          name: Run build
          command: bash build.sh
      - run:
          name: Deploy to GitHub releases
          command: bash release.sh
      - store_artifacts:
          path: release
          destination: packages
  "4.19.28":
    working_directory: ~/code
    docker:
      - image: pexcn/docker-images:stretch-linux-kernel
    environment:
      KERNEL_VERSION: 4.19.28
    steps:
      - checkout
      - run:
          name: Run build
          command: bash build.sh
      - run:
          name: Deploy to GitHub releases
          command: bash release.sh
      - store_artifacts:
          path: release
          destination: packages

workflows:
  version: 2
  build:
    jobs:
      - "4.9.162"
      - "4.14.105"
      - "4.19.28"
