version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: pexcn/docker-images:stretch-linux-kernel
    steps:
      - checkout
      - run:
          name: Run build
          command: bash build.sh
      - run:
          name: Deploy to GitHub releases
          command: bash release.sh
      - store_artifacts:
          path: dist
          destination: packages
